import type { FormSpec } from '../types'

// ============================================================================
// Gera o backend do formulario: uma Serverless Function da Vercel em
// api/save-lead.mjs. E a mesma peca que ja roda nas LPs — normaliza o lead,
// manda pro webhook do n8n e grava no ledger do Supabase em paralelo — so que
// com o slug e o webhook DESTE formulario ja preenchidos.
//
// Por que passar por um endpoint em vez de o formulario chamar o n8n direto:
//   1. a URL do webhook nao fica exposta no bundle do site;
//   2. o servidor valida antes de gravar (nome/whatsapp);
//   3. da pra gravar no ledger em paralelo — se o n8n cair, o lead nao some.
// ============================================================================

export function gerarApiSaveLead(spec: FormSpec): string {
  const slug = spec.destino.slug || 'form'
  const webhook = spec.destino.modo === 'webhook' ? spec.destino.url : ''
  const data = new Date().toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })
  const nomesDeCampo = [
    ...new Set(
      spec.etapas
        .flatMap((e) => e.campos)
        .map((c) => c.name)
        .filter(Boolean),
    ),
  ]
  const nomesFixos = spec.destino.camposFixos.map((f) => f.name).filter(Boolean)
  const trackKeys = [...spec.tracking.utms, ...spec.tracking.clickIds]

  const L: string[] = []
  const p = (...linhas: string[]) => L.push(...linhas)

  p('//  /api/save-lead — backend do formulário')
  p(`//  ${spec.nome}`)
  p(`//  Gerado pelo STFV Forms em ${data}.`)
  p('//')
  p('//  Coloque este arquivo em api/save-lead.mjs na raiz do projeto Vercel.')
  p('//  Ele NÃO precisa de dependência nenhuma (usa fetch nativo do Node 18+).')
  p('//')
  p('//  Env vars (Vercel → Settings → Environment Variables):')
  p('//    WEBHOOK_URL            (opcional) força um webhook único — útil só em debug')
  p('//    SUPABASE_LEADS_URL     (opcional) ledger anti-perda de lead')
  p('//    SUPABASE_LEADS_KEY     (opcional) service_role do mesmo projeto')
  p('')
  p('// slug do formulário → webhook de PRODUÇÃO no n8n')
  p('const WEBHOOKS = {')
  p(`  ${JSON.stringify(slug)}: ${JSON.stringify(webhook || 'COLE_AQUI_O_WEBHOOK_DO_N8N')},`)
  p('}')
  p('')
  p(`const TRACK_KEYS = ${JSON.stringify(trackKeys)}`)
  p('')
  p('// Allowlist: só os campos que ESTE formulário envia entram no lead. Evita')
  p('// mass-assignment e mantém os logs e o webhook limpos.')
  p(`const CAMPOS_DO_FORM = ${JSON.stringify([...nomesFixos, ...nomesDeCampo])}`)
  p('')
  p('/** Payload/CRM sempre recebem +55 + dígitos (ex.: +5542984265706). */')
  p('function normalizarWhatsapp(valor) {')
  p("  const digitos = String(valor || '').replace(/\\D/g, '')")
  p("  const semDDI = digitos.startsWith('55') && digitos.length > 11 ? digitos.slice(2) : digitos")
  p("  return semDDI ? `+55${semDDI}` : ''")
  p('}')
  p('')
  p('function dataHoraSaoPaulo() {')
  p("  const f = new Intl.DateTimeFormat('pt-BR', {")
  p("    timeZone: 'America/Sao_Paulo',")
  p("    day: '2-digit', month: '2-digit', year: 'numeric',")
  p("    hour: '2-digit', minute: '2-digit', second: '2-digit',")
  p('  })')
  p("  return f.format(new Date()).replace(',', '')")
  p('}')
  p('')
  p('export default async function handler(req, res) {')
  p("  if (req.method !== 'POST') {")
  p("    res.status(405).json({ ok: false, error: 'method_not_allowed' })")
  p('    return')
  p('  }')
  p('')
  p("  const body = typeof req.body === 'object' && req.body !== null ? req.body : {}")
  p("  const str = (v, max) => String(v ?? '').slice(0, max)")
  p('')
  p('  const lead = {')
  p('    lead_id: str(body.lead_id, 80) || `lead_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`,')
  p('    form_name: str(body.form_name, 80),')
  p(`    slug: str(body.slug, 40) || ${JSON.stringify(slug)},`)
  p('    timestamp: str(body.timestamp, 40),')
  p('    data_hora_cadastro: dataHoraSaoPaulo(),')
  p("    etapa: str(body.etapa, 30) || 'completo',")
  p('    formulario_completo: body.formulario_completo !== false,')
  p('  }')
  p('  for (const k of CAMPOS_DO_FORM) lead[k] = str(body[k], 300)')
  p('  for (const k of TRACK_KEYS) lead[k] = str(body[k], 200)')
  p("  if ('whatsapp' in lead) lead.whatsapp = normalizarWhatsapp(body.whatsapp)")
  p("  if ('email' in lead) lead.email = str(body.email, 120).toLowerCase().trim()")
  p('')
  p('  // Validação no servidor: o cliente pode ser burlado, o servidor não.')
  p("  if ('nome' in lead && String(lead.nome).trim().length < 2) {")
  p("    res.status(400).json({ ok: false, error: 'nome_invalido' })")
  p('    return')
  p('  }')
  p("  if ('whatsapp' in lead && lead.whatsapp.length < 13) { // +55 + ao menos 10 dígitos")
  p("    res.status(400).json({ ok: false, error: 'whatsapp_invalido' })")
  p('    return')
  p('  }')
  p('')
  p('  // Rede de segurança: todo lead fica nos logs da função')
  p("  console.log('[lead]', JSON.stringify(lead))")
  p('')
  p('  const webhookUrl = process.env.WEBHOOK_URL || WEBHOOKS[lead.slug]')
  p('  const slugOk = Boolean(webhookUrl)')
  p('')
  p('  // ── Canal 1: webhook do n8n ───────────────────────────────────────────')
  p('  const enviarN8n = async () => {')
  p('    if (!webhookUrl) {')
  p('      console.warn(`[webhook] sem destino para slug="${lead.slug}" — coberto pelo ledger`)')
  p('      return')
  p('    }')
  p('    const ctrl = new AbortController()')
  p('    const timeout = setTimeout(() => ctrl.abort(), 7000)')
  p('    try {')
  p('      const resp = await fetch(webhookUrl, {')
  p("        method: 'POST',")
  p("        headers: { 'Content-Type': 'application/json' },")
  p('        body: JSON.stringify(lead),')
  p('        signal: ctrl.signal,')
  p('      })')
  p("      if (!resp.ok) console.error('[webhook] status', resp.status)")
  p('    } finally {')
  p('      clearTimeout(timeout)')
  p('    }')
  p('  }')
  p('')
  p('  // ── Canal 2: ledger no Supabase (independe do n8n) ────────────────────')
  p('  // Captura 100% dos leads — inclusive se o n8n estiver fora do ar. Falha aqui')
  p('  // NUNCA trava o usuário nem perde o lead: só vira log.')
  p('  const gravarLedger = async () => {')
  p('    const SB_URL = process.env.SUPABASE_LEADS_URL')
  p('    const SB_KEY = process.env.SUPABASE_LEADS_KEY')
  p('    if (!SB_URL || !SB_KEY) {')
  p("      console.warn('[ledger] SUPABASE_LEADS_URL/KEY ausentes — lead só no n8n/logs')")
  p('      return')
  p('    }')
  p('    const ctrl = new AbortController()')
  p('    const timeout = setTimeout(() => ctrl.abort(), 7000)')
  p('    try {')
  p("      const resp = await fetch(`${SB_URL.replace(/\\/$/, '')}/rest/v1/site_leads`, {")
  p("        method: 'POST',")
  p('        headers: {')
  p('          apikey: SB_KEY,')
  p('          Authorization: `Bearer ${SB_KEY}`,')
  p("          'Content-Type': 'application/json',")
  p("          Prefer: 'return=minimal',")
  p('        },')
  p('        body: JSON.stringify({')
  p('          lead_id: lead.lead_id,')
  p("          site: 'trafego',")
  p('          slug: lead.slug,')
  p('          slug_ok: slugOk,')
  p("          form_name: lead.form_name || '',")
  p("          nome: lead.nome || '',")
  p("          whatsapp: lead.whatsapp || '',")
  p("          email: lead.email || '',")
  p("          instagram: lead.instagram || '',")
  p("          expedicao: lead.expedicao || '',")
  p("          fonte: lead.fonte || '',")
  p("          source_id: lead.source_id || '',")
  p("          data_hora_cadastro: lead.data_hora_cadastro || '',")
  p('          raw: lead,')
  p('        }),')
  p('        signal: ctrl.signal,')
  p('      })')
  p('      // 409 = lead_id repetido (re-submit) = já capturado, não é erro.')
  p('      if (!resp.ok && resp.status !== 409) {')
  p("        const txt = await resp.text().catch(() => '')")
  p("        console.error('[ledger] status', resp.status, txt)")
  p('      }')
  p('    } finally {')
  p('      clearTimeout(timeout)')
  p('    }')
  p('  }')
  p('')
  p('  // Os dois canais correm em PARALELO: nenhum atrasa o outro.')
  p('  const [rN8n, rLedger] = await Promise.allSettled([enviarN8n(), gravarLedger()])')
  p("  if (rN8n.status === 'rejected') console.error('[webhook] falhou:', rN8n.reason?.message)")
  p("  if (rLedger.status === 'rejected') console.error('[ledger] falhou:', rLedger.reason?.message)")
  p('')
  p('  res.status(200).json({ ok: true })')
  p('}')

  return L.join('\n')
}
