-- Publica os 6 formularios das lives de setembro/2026, um por expedicao.
-- Foi ESTE SQL que rodou em 03/09/2026 no SQL editor do Supabase do Dashboard
-- (pkdcglrzbjvcedlizqqv). O html de cada linha e derivado por replace() do html
-- que ja estava no banco (/f/live, Tailandia) e o spec por jsonb_set: as cadeias
-- foram conferidas byte a byte contra a geracao local pelo _gerador.mjs do HEAD,
-- e os md5 devolvidos bateram com os esperados.
--   amalfitana f90227008f12f353276b50f79a89338e
--   tailandia  9f05b3c83d140c197367c37cbda21d0c
--   turquia    07c443db970fb217a3d529cecff5911a
--   islandia   1943a23ed36a68fcc1b0b4a5a3730146
--   japao      a657fa7740417a3292eb19a15afa0e79
--   egito      5c486d017def66086bf05460dd89643b
with o as (select spec,html from stfv_forms_publicados where slug='live')
insert into stfv_forms_publicados (slug,nome,spec,html,atualizado_em)
select 'amalfitana','Live Costa Amalfitana — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_amalfitana'::text)),'{nome}',to_jsonb('Live Costa Amalfitana — captação'::text)),'{slug}',to_jsonb('amalfitana'::text)),'{destino,slug}',to_jsonb('amalfitana'::text)),'{destino,formName}',to_jsonb('live-costa-amalfitana-2026'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live da Costa Amalfitana e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-amalfitana'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.461Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_ITALIA"},{"id":"cf_fonte","name":"fonte","valor":"[Itália] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Costa Amalfitana"}]'::jsonb),
  replace(replace(replace(replace(replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Costa Amalfitana — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "amalfitana"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-amalfitana"'),'Assisti a live e quero seguir os próximos passos','Assisti a live da Costa Amalfitana e quero seguir os próximos passos'),'live-tailandia-2026','live-costa-amalfitana-2026'),'LIVE_TAILANDIA','LIVE_ITALIA'),'[Tailândia] - Live','[Itália] - Live'),'"expedicao": "Tailândia"','"expedicao": "Costa Amalfitana"'),now() from o
union all
select 'tailandia','Live Tailândia — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_tailandia'::text)),'{nome}',to_jsonb('Live Tailândia — captação'::text)),'{slug}',to_jsonb('tailandia'::text)),'{destino,slug}',to_jsonb('tailandia'::text)),'{destino,formName}',to_jsonb('live-tailandia-2026'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live da Tailândia e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-tailandia'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.553Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_TAILANDIA"},{"id":"cf_fonte","name":"fonte","valor":"[Tailândia] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Tailândia"}]'::jsonb),
  replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Tailândia — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "tailandia"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-tailandia"'),'Assisti a live e quero seguir os próximos passos','Assisti a live da Tailândia e quero seguir os próximos passos'),now() from o
union all
select 'turquia','Live Turquia e Grécia — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_turquia'::text)),'{nome}',to_jsonb('Live Turquia e Grécia — captação'::text)),'{slug}',to_jsonb('turquia'::text)),'{destino,slug}',to_jsonb('turquia'::text)),'{destino,formName}',to_jsonb('live-turquia-grecia-2026'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live da Turquia e Grécia e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-turquia'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.563Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_TURQUIA_GRECIA"},{"id":"cf_fonte","name":"fonte","valor":"[Turquia e Grécia] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Turquia e Grécia"}]'::jsonb),
  replace(replace(replace(replace(replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Turquia e Grécia — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "turquia"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-turquia"'),'Assisti a live e quero seguir os próximos passos','Assisti a live da Turquia e Grécia e quero seguir os próximos passos'),'live-tailandia-2026','live-turquia-grecia-2026'),'LIVE_TAILANDIA','LIVE_TURQUIA_GRECIA'),'[Tailândia] - Live','[Turquia e Grécia] - Live'),'"expedicao": "Tailândia"','"expedicao": "Turquia e Grécia"'),now() from o
union all
select 'islandia','Live Islândia — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_islandia'::text)),'{nome}',to_jsonb('Live Islândia — captação'::text)),'{slug}',to_jsonb('islandia'::text)),'{destino,slug}',to_jsonb('islandia'::text)),'{destino,formName}',to_jsonb('live-islandia-2026'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live da Islândia e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-islandia'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.567Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_ISLANDIA"},{"id":"cf_fonte","name":"fonte","valor":"[Islândia] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Islândia"}]'::jsonb),
  replace(replace(replace(replace(replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Islândia — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "islandia"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-islandia"'),'Assisti a live e quero seguir os próximos passos','Assisti a live da Islândia e quero seguir os próximos passos'),'live-tailandia-2026','live-islandia-2026'),'LIVE_TAILANDIA','LIVE_ISLANDIA'),'[Tailândia] - Live','[Islândia] - Live'),'"expedicao": "Tailândia"','"expedicao": "Islândia"'),now() from o
union all
select 'japao','Live Japão e China — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_japao'::text)),'{nome}',to_jsonb('Live Japão e China — captação'::text)),'{slug}',to_jsonb('japao'::text)),'{destino,slug}',to_jsonb('japao'::text)),'{destino,formName}',to_jsonb('live-japao-china-2027'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live do Japão e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-japao'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.577Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_JAPAO_CHINA"},{"id":"cf_fonte","name":"fonte","valor":"[Japão e China] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Japão e China"}]'::jsonb),
  replace(replace(replace(replace(replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Japão e China — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "japao"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-japao"'),'Assisti a live e quero seguir os próximos passos','Assisti a live do Japão e quero seguir os próximos passos'),'live-tailandia-2026','live-japao-china-2027'),'LIVE_TAILANDIA','LIVE_JAPAO_CHINA'),'[Tailândia] - Live','[Japão e China] - Live'),'"expedicao": "Tailândia"','"expedicao": "Japão e China"'),now() from o
union all
select 'egito','Live Egito — captação',
  jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(o.spec,'{id}',to_jsonb('form_live_egito'::text)),'{nome}',to_jsonb('Live Egito — captação'::text)),'{slug}',to_jsonb('egito'::text)),'{destino,slug}',to_jsonb('egito'::text)),'{destino,formName}',to_jsonb('live-egito-2026'::text)),'{destino,whatsappMensagem}',to_jsonb('Assisti a live do Egito e quero seguir os próximos passos'::text)),'{tracking,fallbackUtmContent}',to_jsonb('live-egito'::text)),'{atualizadoEm}',to_jsonb('2026-09-03T20:27:58.586Z'::text)),'{destino,camposFixos}','[{"id":"cf_source","name":"source_id","valor":"LIVE_EGITO"},{"id":"cf_fonte","name":"fonte","valor":"[Egito] - Live"},{"id":"cf_exped","name":"expedicao","valor":"Egito"}]'::jsonb),
  replace(replace(replace(replace(replace(replace(replace(replace(replace(o.html,'Live Tailândia — captacao','Live Egito — captação'),'em 24/08/2026, 12:09:21','em 03/09/2026, 17:27:58'),'var SLUG = "live"','var SLUG = "egito"'),'var FALLBACK_UTM_CONTENT = "live"','var FALLBACK_UTM_CONTENT = "live-egito"'),'Assisti a live e quero seguir os próximos passos','Assisti a live do Egito e quero seguir os próximos passos'),'live-tailandia-2026','live-egito-2026'),'LIVE_TAILANDIA','LIVE_EGITO'),'[Tailândia] - Live','[Egito] - Live'),'"expedicao": "Tailândia"','"expedicao": "Egito"'),now() from o
on conflict (slug) do update set nome=excluded.nome,spec=excluded.spec,html=excluded.html,atualizado_em=now()
returning slug,md5(html) as md5_html,spec->'destino'->'camposFixos'->0->>'valor' as fonte_id;